name: markdown_editor
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/konrad1001/note_demo/packages/markdown_editor"

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


# flutter:
