name: note_demo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  diff_match_patch: ^0.4.1
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^3.0.3
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+8
  path_provider: ^2.1.5
  window_manager: ^0.5.1
  hive_ce: ^2.15.1
  crypto: ^3.0.7
  shimmer_animation: ^2.1.0
  graphview: ^1.5.1
  markdown_editor: 
    path: ../packages/markdown_editor
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^3.0.3
  custom_lint: ^0.8.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  gemini_agent_tools: ^0.0.3

flutter:
  uses-material-design: true
